//! Local protobuf automation extension command: `just x proto ...`.

use std::path::Path;
use std::path::PathBuf;

use bpaf::OptionParser;
use bpaf::Parser as _;
use bpaf::construct;
use bpaf::pure;
use strict_standard::EnvironmentChange;
use strict_standard::OutputPolicy;
use strict_standard::PathState;
use template_core::cli::context::CommandContext;
use template_core::cli::extension::ExtensionCommand;
use template_core::cli::extension::extension_command;
use template_core::cli::output::StatusKind;
use template_core::cli::output::plain;
use template_core::sys::process::ToolColor;
use template_core::sys::process::require_success;

use crate::extensions::ProjectCommand;
use crate::workspace;

/// The exact `protoc --version` output required by this repository.
pub(crate) const EXPECTED_PROTOC_VERSION: &str = "libprotoc 35.1";

/// Committed `prost` binding regenerated by `build.rs`.
const PROST_GENERATED_BINDING: &str = "proto/perftools.profiles.rs";

/// Parsed arguments for `just x proto`.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum Args {
  /// Install and validate the pinned `protoc` tool.
  Setup,
  /// Force-refresh committed generated protobuf artifacts.
  Update,
  /// Run generation-driving codec checks without forcing a refresh first.
  Gen,
}

/// Validated protobuf toolchain paths.
#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct Toolchain {
  /// Absolute or shim-resolved `protoc` path returned by `proto`.
  protoc: String,
}

impl Toolchain {
  /// Return the validated `protoc` path.
  #[must_use]
  pub(crate) fn protoc(&self) -> &str {
    &self.protoc
  }

  /// Render a short human-facing summary.
  fn summary(&self) -> String {
    format!("{} at {}", EXPECTED_PROTOC_VERSION, self.protoc)
  }
}

/// A generation-driving Cargo step definition.
#[derive(Clone, Debug, Eq, PartialEq)]
struct GenerationStepSpec {
  /// Human-facing step label.
  label:    &'static str,
  /// Codec feature that drives the generation path.
  features: &'static str,
}

/// Cargo checks that drive the committed and `OUT_DIR` protobuf generation paths.
const GENERATION_STEPS: &[GenerationStepSpec] = &[
  GenerationStepSpec {
    label:    "generate prost bindings",
    features: "prost-codec",
  },
  GenerationStepSpec {
    label:    "generate protobuf bindings",
    features: "protobuf-codec",
  },
];

/// One generation-driving Cargo step.
#[derive(Clone, Debug, Eq, PartialEq)]
struct GenerationStep {
  /// Human-facing step label.
  label: &'static str,
  /// Cargo arguments for the step.
  args:  Vec<String>,
}

/// Backup of the committed generated binding before a forced refresh.
#[derive(Clone, Debug, Eq, PartialEq)]
struct GeneratedBindingBackup {
  /// Path that was removed for regeneration.
  path: PathBuf,
  /// Original exact file bytes, if the file existed.
  body: Option<Vec<u8>>,
}

impl GeneratedBindingBackup {
  /// Restore the original file only when regeneration left it absent.
  ///
  /// # Errors
  ///
  /// Returns an I/O error if the path cannot be queried or restored.
  fn restore_if_missing(&self, context: &CommandContext) -> template_core::Result<()> {
    let Some(body) = self.body.as_ref() else {
      return Ok(());
    };
    if context.file_system().path_state(&self.path)? == PathState::Missing {
      context.file_system().write_bytes(&self.path, body)?;
    }
    Ok(())
  }
}

/// Declare the command's `bpaf` options.
#[allow(
  clippy::single_call_fn,
  reason = "a named options() keeps the extension parser beside the proto command it configures"
)]
fn options() -> OptionParser<Args> {
  let setup = pure(Args::Setup)
    .to_options()
    .descr("Install and validate pinned protoc")
    .command("setup");
  let update = pure(Args::Update)
    .to_options()
    .descr("Force-refresh committed protobuf artifacts")
    .command("update");
  let gen_parser = pure(Args::Gen)
    .to_options()
    .descr("Run protobuf generation checks")
    .command("gen");

  construct!([setup, update, gen_parser])
    .to_options()
    .descr("Run pprof protobuf maintenance commands")
}

/// Run the proto extension command.
///
/// # Errors
///
/// Returns a workflow error when the pinned `protoc` version is unavailable or
/// invalid, returns I/O errors while forcing committed binding regeneration,
/// and returns process errors from failed generation steps.
#[allow(
  clippy::single_call_fn,
  reason = "extension dispatch calls the handler once through ProjectCommand::run"
)]
pub(crate) fn execute(context: &CommandContext, args: Args) -> template_core::Result<()> {
  execute_with_root(context, args, &workspace::root()?)
}

/// Registry entry point referenced from `xtask/src/extensions.rs`.
#[must_use]
#[allow(
  clippy::single_call_fn,
  reason = "the command() seam is consumed once by the local extension registry"
)]
pub(crate) fn command() -> template_core::Result<ExtensionCommand<ProjectCommand>> {
  extension_command(
    "proto",
    "Run protobuf setup, update, and generation helpers",
    options(),
    ProjectCommand::Proto,
  )
}

/// Install and validate the pinned `protoc` binary.
///
/// # Errors
///
/// Returns process errors from `proto` or `protoc`, and returns a workflow error
/// if `proto` reports no path or `protoc --version` is not the expected version.
pub(crate) fn setup_toolchain(context: &CommandContext) -> template_core::Result<Toolchain> {
  context.status(StatusKind::Probe, plain("installing pinned protoc"))?;
  let install_arguments = vec!["install".to_owned(), "protoc".to_owned()];
  let install_request = context.process_request(
    "proto",
    &install_arguments,
    ToolColor::EnvOnly,
    OutputPolicy::Inherit,
    OutputPolicy::Inherit,
    &[],
  );
  let install_output = context.execute_process(&install_request)?;
  drop(require_success(&install_request, install_output)?);

  let locate_arguments = vec![
    "--reporter".to_owned(),
    "text".to_owned(),
    "bin".to_owned(),
    "protoc".to_owned(),
  ];
  let locate_request = context.process_request(
    "proto",
    &locate_arguments,
    ToolColor::CapturedPlain,
    OutputPolicy::Capture,
    OutputPolicy::Inherit,
    &[],
  );
  let locate_output = context.execute_process(&locate_request)?;
  let located = require_success(&locate_request, locate_output)?;
  let protoc = String::from_utf8_lossy(&located.stdout).trim().to_owned();
  if protoc.is_empty() {
    return Err(workflow_error("proto returned an empty protoc path"));
  }

  let version_arguments = vec!["--version".to_owned()];
  let version_request = context.process_request(
    &protoc,
    &version_arguments,
    ToolColor::CapturedPlain,
    OutputPolicy::Capture,
    OutputPolicy::Inherit,
    &[],
  );
  let version_output = context.execute_process(&version_request)?;
  let observed_version = require_success(&version_request, version_output)?;
  let version_text = String::from_utf8_lossy(&observed_version.stdout);
  let version = version_text.trim();
  if version != EXPECTED_PROTOC_VERSION {
    return Err(workflow_error(format!(
      "expected `{EXPECTED_PROTOC_VERSION}` from `{protoc} --version`, got `{version}`"
    )));
  }

  Ok(Toolchain {
    protoc,
  })
}

/// Run `just x proto ...` with an explicit workspace root.
///
/// # Errors
///
/// Returns setup, I/O, or generation process errors for the selected command.
#[allow(
  clippy::single_call_fn,
  reason = "explicit-root execution lets update/gen tests exercise file effects without touching the real repository"
)]
pub(crate) fn execute_with_root(context: &CommandContext, args: Args, root: &Path) -> template_core::Result<()> {
  match args {
    Args::Setup => run_setup(context),
    Args::Update => run_update(context, root),
    Args::Gen => run_gen(context, root),
  }
}

/// Run the setup subcommand.
#[allow(
  clippy::single_call_fn,
  reason = "setup has distinct user-facing output after toolchain validation"
)]
fn run_setup(context: &CommandContext) -> template_core::Result<()> {
  let toolchain = setup_toolchain(context)?;
  context.status(StatusKind::Ok, plain(format!("proto: {}", toolchain.summary())))
}

/// Run the update subcommand.
#[allow(
  clippy::single_call_fn,
  reason = "update combines forced artifact refresh with rollback-on-generation-failure semantics"
)]
fn run_update(context: &CommandContext, root: &Path) -> template_core::Result<()> {
  let toolchain = setup_toolchain(context)?;
  let backup = force_refresh_prost_binding(context, root)?;
  match run_generation_checks(context, root, &toolchain) {
    Ok(()) => Ok(()),
    Err(error) => {
      backup.restore_if_missing(context)?;
      Err(error)
    }
  }
}

/// Run the gen subcommand.
#[allow(
  clippy::single_call_fn,
  reason = "gen names the non-mutating generation-driving path separately from forced update"
)]
fn run_gen(context: &CommandContext, root: &Path) -> template_core::Result<()> {
  let toolchain = setup_toolchain(context)?;
  run_generation_checks(context, root, &toolchain)
}

/// Remove the committed `prost` artifact so `build.rs` must regenerate it.
#[allow(
  clippy::single_call_fn,
  reason = "the forced-refresh filesystem operation is isolated so rollback semantics stay visible"
)]
fn force_refresh_prost_binding(context: &CommandContext, root: &Path) -> template_core::Result<GeneratedBindingBackup> {
  let path = root.join(PROST_GENERATED_BINDING);
  context.status(StatusKind::Info, plain(format!("proto: refreshing {PROST_GENERATED_BINDING}")))?;
  let body = if context.file_system().path_state(&path)? == PathState::Missing {
    None
  } else {
    let body = context.file_system().read_bytes(&path)?;
    context.file_system().remove_path(&path)?;
    Some(body)
  };
  Ok(GeneratedBindingBackup {
    path,
    body,
  })
}

/// Run Cargo checks that drive both protobuf generation paths.
fn run_generation_checks(context: &CommandContext, root: &Path, toolchain: &Toolchain) -> template_core::Result<()> {
  for step in generation_steps(root) {
    context.status(StatusKind::Info, plain(format!("proto: {}", step.label)))?;
    let environment = [EnvironmentChange::Set {
      name:  "PROTOC".into(),
      value: toolchain.protoc().into(),
    }];
    let request = context.process_request(
      "cargo",
      &step.args,
      ToolColor::CargoGlobal,
      OutputPolicy::Inherit,
      OutputPolicy::Inherit,
      &environment,
    );
    let output = context.execute_process(&request)?;
    drop(require_success(&request, output)?);
  }
  Ok(())
}

/// Build generation-driving Cargo steps.
#[allow(
  clippy::single_call_fn,
  reason = "generation step construction is test-pinned separately from command execution"
)]
fn generation_steps(root: &Path) -> Vec<GenerationStep> {
  GENERATION_STEPS
    .iter()
    .map(|step| GenerationStep {
      label: step.label,
      args:  cargo_args("check", root, &["--features", step.features, "--locked"]),
    })
    .collect()
}

/// Build Cargo arguments with an absolute manifest path.
#[allow(
  clippy::single_call_fn,
  reason = "proto generation checks share the same manifest anchoring contract"
)]
fn cargo_args(subcommand: &str, root: &Path, args: &[&str]) -> Vec<String> {
  let mut owned = vec![
    subcommand.to_owned(),
    "--manifest-path".to_owned(),
    root.join("Cargo.toml").display().to_string(),
  ];
  owned.extend(args.iter().map(|arg| (*arg).to_owned()));
  owned
}

/// Build a workflow-specific error.
pub(crate) fn workflow_error(message: impl Into<String>) -> template_core::CoreError {
  crate::error::workflow(message)
}

#[cfg(test)]
mod tests {
  use std::path::Path;
  use std::path::PathBuf;

  use strict_standard::OutputPolicy;
  use strict_standard::ProcessRequest;
  use strict_test_support::EffectEvent;
  use strict_test_support::TestFailure;
  use strict_test_support::ensure;
  use strict_test_support::ensure_ok;
  use strict_test_support::ensure_some;
  use template_core::CoreError;
  use template_core::cli::context::CommandContext;
  use template_core::sys::process::ToolColor;

  use super::Args;
  use super::EXPECTED_PROTOC_VERSION;
  use super::PROST_GENERATED_BINDING;
  use super::execute_with_root;
  use super::generation_steps;
  use super::options;
  use super::setup_toolchain;
  use crate::test_support::ProcessFixture;
  use crate::test_support::expected_setup_requests;
  use crate::test_support::extension_request;
  use crate::test_support::protoc_environment;
  use crate::test_support::recording_context;

  #[test]
  fn parser_selects_each_proto_subcommand() -> Result<(), TestFailure> {
    ensure(
      options().run_inner(&["setup"]).ok() == Some(Args::Setup),
      "setup subcommand must parse",
    )?;
    ensure(
      options().run_inner(&["update"]).ok() == Some(Args::Update),
      "update subcommand must parse",
    )?;
    ensure(options().run_inner(&["gen"]).ok() == Some(Args::Gen), "gen subcommand must parse")
  }

  #[test]
  fn parser_rejects_missing_or_unknown_subcommands() -> Result<(), TestFailure> {
    ensure(options().run_inner(&[]).is_err(), "proto parser must require a subcommand")?;
    ensure(
      options().run_inner(&["build"]).is_err(),
      "proto parser must reject unknown subcommands",
    )
  }

  #[test]
  fn setup_records_proto_install_and_version_check() -> Result<(), TestFailure> {
    let fixtures = [
      ProcessFixture::Success,
      ProcessFixture::Stdout("/tool/protoc\n"),
      ProcessFixture::Stdout("libprotoc 35.1\n"),
    ];
    let (context, recorder) = recording_context(&fixtures)?;
    let toolchain = ensure_ok(setup_toolchain(&context), "setup should succeed with a matching protoc version")?;

    ensure(toolchain.protoc() == "/tool/protoc", "setup must return the validated protoc path")?;
    ensure(
      recorder.process_requests() == expected_setup_requests(&context, "/tool/protoc"),
      "setup must install protoc, resolve its path, and validate its version",
    )
  }

  #[test]
  fn setup_rejects_wrong_protoc_version() -> Result<(), TestFailure> {
    let fixtures = [
      ProcessFixture::Success,
      ProcessFixture::Stdout("/tool/protoc\n"),
      ProcessFixture::Stdout("libprotoc 3.21.12\n"),
    ];
    let (context, recorder) = recording_context(&fixtures)?;
    let error = ensure_some(setup_toolchain(&context).err(), "wrong protoc version must fail setup")?;
    let rendered = error.to_string();

    ensure(
      matches!(error, CoreError::WorkflowFailure { .. }),
      "wrong protoc version must remain a workflow-owned error",
    )?;
    ensure(
      rendered.contains(EXPECTED_PROTOC_VERSION),
      "wrong protoc version must name the expected version",
    )?;
    ensure(
      recorder.process_requests() == expected_setup_requests(&context, "/tool/protoc"),
      "wrong protoc version must stop before generation checks",
    )
  }

  #[test]
  fn setup_rejects_an_empty_protoc_path_before_version_execution() -> Result<(), TestFailure> {
    let fixtures = [ProcessFixture::Success, ProcessFixture::Stdout("\n")];
    let (context, recorder) = recording_context(&fixtures)?;
    let error = ensure_some(setup_toolchain(&context).err(), "empty protoc path must fail setup")?;
    let rendered = error.to_string();

    ensure(
      matches!(error, CoreError::WorkflowFailure { .. }),
      "empty protoc path must remain a workflow-owned error",
    )?;
    ensure(rendered.contains("empty protoc path"), "empty protoc path must explain the validation failure")?;
    let mut expected = expected_setup_requests(&context, "/tool/protoc");
    expected.truncate(2);
    ensure(
      recorder.process_requests() == expected,
      "empty protoc path must stop before attempting a version command",
    )
  }

  #[test]
  fn gen_runs_both_generation_checks_with_protoc() -> Result<(), TestFailure> {
    let root = virtual_root();
    let fixtures = [
      ProcessFixture::Success,
      ProcessFixture::Stdout("/tool/protoc\n"),
      ProcessFixture::Stdout("libprotoc 35.1\n"),
      ProcessFixture::Success,
      ProcessFixture::Success,
    ];
    let (context, recorder) = recording_context(&fixtures)?;

    ensure_ok(
      execute_with_root(&context, Args::Gen, &root),
      "gen should run setup and both generation-driving checks",
    )?;

    let mut expected = expected_setup_requests(&context, "/tool/protoc");
    expected.extend(expected_generation_requests(&context, &root, "/tool/protoc"));
    ensure(
      recorder.process_requests() == expected,
      "gen must run the prost and protobuf codegen checks with PROTOC set",
    )
  }

  #[test]
  fn update_forces_prost_binding_refresh_before_generation() -> Result<(), TestFailure> {
    let root = virtual_root();
    let generated = root.join(PROST_GENERATED_BINDING);
    let fixtures = [
      ProcessFixture::Success,
      ProcessFixture::Stdout("/tool/protoc\n"),
      ProcessFixture::Stdout("libprotoc 35.1\n"),
      ProcessFixture::Success,
      ProcessFixture::Success,
    ];
    let (context, recorder) = recording_context(&fixtures)?;
    recorder.set_file(&generated, b"old generated body".to_vec());

    ensure_ok(
      execute_with_root(&context, Args::Update, &root),
      "update should remove the committed prost artifact before generation checks",
    )?;

    ensure(
      recorder.file_bytes(&generated).is_none(),
      "fake generation leaves the forced-refresh artifact absent",
    )?;
    let setup_events = expected_setup_requests(&context, "/tool/protoc");
    let mut expected = setup_events
      .into_iter()
      .map(EffectEvent::Process)
      .collect::<Vec<EffectEvent>>();
    expected.extend([
      EffectEvent::PathState(generated.clone()),
      EffectEvent::ReadBytes(generated.clone()),
      EffectEvent::RemovePath(generated.clone()),
    ]);
    expected.extend(
      expected_generation_requests(&context, &root, "/tool/protoc")
        .into_iter()
        .map(EffectEvent::Process),
    );
    ensure(
      recorder.events() == expected,
      "update must read and remove the committed binding before both generation-driving checks",
    )
  }

  #[test]
  fn update_restores_original_binding_when_generation_never_recreates_it() -> Result<(), TestFailure> {
    let root = virtual_root();
    let generated = root.join(PROST_GENERATED_BINDING);
    let fixtures = [
      ProcessFixture::Success,
      ProcessFixture::Stdout("/tool/protoc\n"),
      ProcessFixture::Stdout("libprotoc 35.1\n"),
      ProcessFixture::Failure,
    ];
    let (context, recorder) = recording_context(&fixtures)?;
    recorder.set_file(&generated, b"old generated body".to_vec());

    ensure(
      execute_with_root(&context, Args::Update, &root).is_err(),
      "a failing generation check should fail update",
    )?;

    ensure(
      recorder.file_bytes(&generated) == Some(b"old generated body".to_vec()),
      "update must restore the original file if generation leaves it missing",
    )?;
    let setup_events = expected_setup_requests(&context, "/tool/protoc");
    let mut expected = setup_events
      .into_iter()
      .map(EffectEvent::Process)
      .collect::<Vec<EffectEvent>>();
    let first_generation = ensure_some(
      expected_generation_requests(&context, &root, "/tool/protoc").into_iter().next(),
      "generation request fixture must contain the first codec check",
    )?;
    expected.extend([
      EffectEvent::PathState(generated.clone()),
      EffectEvent::ReadBytes(generated.clone()),
      EffectEvent::RemovePath(generated.clone()),
      EffectEvent::Process(first_generation),
      EffectEvent::PathState(generated.clone()),
      EffectEvent::WriteBytes {
        path:     generated,
        contents: b"old generated body".to_vec(),
        atomic:   false,
      },
    ]);
    ensure(
      recorder.events() == expected,
      "failed generation must restore the exact original bytes after observing the binding is absent",
    )
  }

  #[test]
  fn update_does_not_invent_a_missing_binding_during_rollback() -> Result<(), TestFailure> {
    let root = virtual_root();
    let generated = root.join(PROST_GENERATED_BINDING);
    let fixtures = [
      ProcessFixture::Success,
      ProcessFixture::Stdout("/tool/protoc\n"),
      ProcessFixture::Stdout("libprotoc 35.1\n"),
      ProcessFixture::Failure,
    ];
    let (context, recorder) = recording_context(&fixtures)?;

    ensure(
      execute_with_root(&context, Args::Update, &root).is_err(),
      "a failing generation check should fail update when no committed binding exists",
    )?;
    ensure(
      recorder.file_bytes(&generated).is_none(),
      "rollback must not create a binding that was absent before update",
    )?;
    let setup_events = expected_setup_requests(&context, "/tool/protoc");
    let mut expected = setup_events
      .into_iter()
      .map(EffectEvent::Process)
      .collect::<Vec<EffectEvent>>();
    let first_generation = ensure_some(
      expected_generation_requests(&context, &root, "/tool/protoc").into_iter().next(),
      "generation request fixture must contain the first codec check",
    )?;
    expected.extend([
      EffectEvent::PathState(generated),
      EffectEvent::Process(first_generation),
    ]);
    ensure(
      recorder.events() == expected,
      "missing input must skip read, removal, and rollback write effects",
    )
  }

  #[test]
  fn generation_step_arguments_are_stable() -> Result<(), TestFailure> {
    let root = virtual_root();
    let manifest = manifest_path(&root);
    let args = generation_steps(&root)
      .into_iter()
      .map(|step| step.args)
      .collect::<Vec<Vec<String>>>();
    ensure(
      args
        == [
          owned_arguments(&[
            "check",
            "--manifest-path",
            &manifest,
            "--features",
            "prost-codec",
            "--locked",
          ]),
          owned_arguments(&[
            "check",
            "--manifest-path",
            &manifest,
            "--features",
            "protobuf-codec",
            "--locked",
          ]),
        ],
      "generation steps must remain the focused prost/protobuf checks",
    )
  }

  fn virtual_root() -> PathBuf {
    PathBuf::from("/workspace")
  }

  fn manifest_path(root: &Path) -> String {
    root.join("Cargo.toml").display().to_string()
  }

  fn expected_generation_requests(context: &CommandContext, root: &Path, protoc: &str) -> Vec<ProcessRequest> {
    let manifest = manifest_path(root);
    let environment = protoc_environment(protoc);
    vec![
      extension_request(
        context,
        "cargo",
        &[
          "check",
          "--manifest-path",
          &manifest,
          "--features",
          "prost-codec",
          "--locked",
        ],
        ToolColor::CargoGlobal,
        OutputPolicy::Inherit,
        &environment,
      ),
      extension_request(
        context,
        "cargo",
        &[
          "check",
          "--manifest-path",
          &manifest,
          "--features",
          "protobuf-codec",
          "--locked",
        ],
        ToolColor::CargoGlobal,
        OutputPolicy::Inherit,
        &environment,
      ),
    ]
  }

  fn owned_arguments(arguments: &[&str]) -> Vec<String> {
    arguments.iter().map(|argument| (*argument).to_owned()).collect()
  }
}
